database:
  db_type: sqlite
  sqlite_db_path: "intelli_bridge.db"
  mysql_user: ""
  mysql_password: ""
  mysql_host: ""
  mysql_database: ""

# 定时任务配置
scheduler:
  invalid_service_interval: 600  # 无效服务扫描间隔（秒）
  valid_service_interval: 1800   # 有效服务扫描间隔（秒）